### ISSUE TITLE
Migrate Visualizations to React

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3301]
This is an issue to track the migration of visualizations code to React:

- [x] Migrate visualizations wrapper (#3493)
- [x] Migrate visualizations:
    - [x] Counter (#4106)
    - [x] Chart
        - [x] Renderer (#4130)
        - [x] Editor (getredash/redash#4139)
    - [x] Table
        - [x] Renderer (#3963)
        - [x] Editor (getredash/redash#4175)
    - [x] Pivot Table
        - [x] Renderer (#4133)
        - [x] Editor
    - [x] Choropleth (getredash/redash#4313)
    - [x] Cohort (getredash/redash#4270)
    - [x] Funnel (getredash/redash#4267)
    - [x] Map (getredash/redash#4278)
    - [x] Sankey
        - [x] Renderer (getredash/redash#4255)
        - [x] Editor
    - [x] Sunburst
        - [x] Renderer (getredash/redash#4259)
        - [x] Editor
    - [x] Word Cloud (#3930)
    - [x] Box Plot (#3948)

**Comment by arikfr** [comment]
We should consider using https://github.com/plotly/react-pivottable#readme when switching the Pivot Table visualization to React.

**Comment by arikfr** [comment]
🎉 All the visualizations are now in React. 🎉
